config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/server_error'
  mount(GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql') if Rails.env.development?

  post '/graphql', to: 'graphql#execute'

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  resources :task_trackers

  post '/entities/process-file', to: 'entities#process_file'

  resources :candidate_products do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :candidate_roles do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :glossaries
  resources :settings

  resources :rubric_categories, only: %i[index update create destroy]
  resources :category_indicators, only: %i[index update create destroy]
  resources :maturity_rubrics do
    resources :rubric_categories do
      resources :category_indicators
    end
  end

  resources :moves, only: %i[index update create destroy]
  resources :activities, only: %i[index update create destroy]

  resources :plays do
    resources :moves
  end

  resources :playbooks do
    post 'assign_play'
    post 'remove_play'
    resources :plays do
      resources :moves
    end
  end

  resources :handbook_pages, only: %i[index update create destroy]
  resources :handbooks do
    get 'count', on: :collection
    post 'upload_design_images', on: :collection
    member do
      post 'convert_pages'
    end
    resources :handbook_pages do
      member do
        get 'copy_page'
        get 'edit_content'
        get 'load_design'
        post 'save_design'
        patch 'save_design'
        get 'create_pdf'
        get 'show_pdf'
      end
    end
  end

  resources :tags
  resources :use_case_steps

  resources :projects do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_project'
      post 'unfavorite_project'
    end
  end

  get 'deploys/index'
  get 'about/learnmore'
  get 'about', to: 'about#index'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  scope '/devise' do
    resources :users do
      get 'statistics', on: :collection
      get 'export_data', on: :collection
    end
  end

  devise_scope :user do
    get '/users', to: 'users#index'
    get '/users/password', to: 'devise/passwords#new'
    post '/authenticate/credentials', to: 'authentication#sign_in_ux'
    post '/authenticate/auth0', to: 'authentication#sign_in_auth0'
    post '/authenticate/signup', to: 'authentication#sign_up_ux'
    get '/authenticate/token', to: 'authentication#fetch_token'
    delete '/auth/invalidate', to: 'authentication#invalidate_token'
    post '/auth/reset-password', to: 'authentication#reset_password'
    post '/auth/apply-reset-token', to: 'authentication#apply_reset_token'
    post '/auth/validate-reset-token', to: 'authentication#validate_reset_token'
  end

  root to: redirect(path: '/products')

  resources :covid, only: [:index]

  resources :candidate_organizations do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :portal_views do
    member do
      post 'select'
    end
  end

  resources :products do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_product'
      post 'unfavorite_product'
    end
  end

  resources :building_blocks do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :sustainable_development_goals, only: %i[index show] do
    get 'count', on: :collection
  end

  resources :sdg_targets, only: %i[index show]

  resources :use_case_steps, only: %i[new create edit update show]
  resources :use_cases do
    get 'count', on: :collection
    get 'export_data', on: :collection
    resources :use_case_steps, only: %i[new create edit update show]
    member do
      post 'favorite_use_case'
      post 'unfavorite_use_case'
    end
  end

  resources :workflows do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :deploys do
    get 'show_messages'
    post 'add_ssh_user'
  end

  resources :organizations do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  get :update_locale, controller: 'application'

  # Start of external API routes
  get 'api/v1/organizations/:id', to: 'organizations#unique_search'
  get 'api/v1/organizations', to: 'organizations#simple_search', defaults: { format: 'json' }
  post 'api/v1/organizations', to: 'organizations#complex_search', defaults: { format: 'json' }

  get 'api/v1/building_blocks/:id', to: 'building_blocks#unique_search'
  get 'api/v1/building_blocks', to: 'building_blocks#simple_search', defaults: { format: 'json' }
  post 'api/v1/building_blocks', to: 'building_blocks#complex_search', defaults: { format: 'json' }

  get 'api/v1/cities/:id', to: 'cities#unique_search'
  get 'api/v1/cities', to: 'cities#simple_search', defaults: { format: 'json' }

  get 'api/v1/countries/:id', to: 'countries#unique_search'
  get 'api/v1/countries', to: 'countries#simple_search', defaults: { format: 'json' }

  get 'api/v1/products/:id', to: 'products#unique_search'
  get 'api/v1/products', to: 'products#simple_search', defaults: { format: 'json' }
  post 'api/v1/products', to: 'products#complex_search', defaults: { format: 'json' }
  post 'api/v1/products/owners', to: 'products#owner_search', defaults: { format: 'json' }

  get 'api/v1/projects/:id', to: 'projects#unique_search'
  get 'api/v1/projects', to: 'projects#simple_search', defaults: { format: 'json' }
  post 'api/v1/projects', to: 'projects#complex_search', defaults: { format: 'json' }

  get 'api/v1/sectors/:id', to: 'sectors#unique_search'
  get 'api/v1/sectors', to: 'sectors#simple_search', defaults: { format: 'json' }

  get 'api/v1/sdgs/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sdgs', to: 'sustainable_development_goals#simple_search', defaults: { format: 'json' }
  post 'api/v1/sdgs', to: 'sustainable_development_goals#simple_search', defaults: { format: 'json' }

  get 'api/v1/sustainable_development_goals/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sustainable_development_goals', to: 'sustainable_development_goals#simple_search',
                                              defaults: { format: 'json' }

  get 'api/v1/tags/:id', to: 'tags#unique_search'
  get 'api/v1/tags', to: 'tags#simple_search', defaults: { format: 'json' }

  get 'api/v1/use_cases/:id', to: 'use_cases#unique_search'
  get 'api/v1/use_cases', to: 'use_cases#simple_search', defaults: { format: 'json' }
  post 'api/v1/use_cases', to: 'use_cases#complex_search', defaults: { format: 'json' }

  get 'api/v1/use_cases/:id/use_case_steps/:step_id', to: 'use_case_steps#unique_search'
  get 'api/v1/use_cases/:id/use_case_steps', to: 'use_case_steps#simple_search', defaults: { format: 'json' }

  get 'api/v1/workflows/:id', to: 'workflows#unique_search'
  get 'api/v1/workflows', to: 'workflows#simple_search', defaults: { format: 'json' }
  post 'api/v1/workflows', to: 'workflows#complex_search', defaults: { format: 'json' }

  # End of external API routes

  resources :operator_services
  resources :audits, only: [:index]
  resources :stylesheets

  resources :cities, only: %i[index show]
  resources :countries

  resources :locations do
    resources :organizations
  end

  resources :sectors do
    resources :organizations
    resources :use_cases
  end

  resources :contacts do
    resources :organizations
  end

  resources :tags
  resources :use_case_steps

  get '/object_counts', to: 'application#object_counts', as: :object_counts
  post '/add_filter', to: 'application#add_filter', as: :add_filter
  post '/add_filters', to: 'application#add_filters', as: :add_filters
  post '/remove_filter', to: 'application#remove_filter', as: :remove_filter
  post '/remove_all_filters', to: 'application#remove_all_filters', as: :remove_all_filters
  get '/fetch_filters', to: 'application#fetch_filters', as: :fetch_filters
  get '/agg_capabilities', to: 'organizations#agg_capabilities', as: :agg_capabilities
  get '/agg_services', to: 'organizations#agg_services', as: :agg_services
  get '/service_capabilities', to: 'organizations#service_capabilities', as: :service_capabilities
  get '/update_capability', to: 'organizations#update_capability', as: :update_capability
  get '/privacy', to: 'about#privacy', as: :privacy
  get '/terms', to: 'about#terms', as: :terms
  get '/healthcheck', to: 'about#healthcheck', as: :healthcheck

  post '/save_url', to: 'application#save_url', as: :save_url
  post '/remove_url', to: 'application#remove_url', as: :remove_url
  post '/send_email', to: 'application#send_email', as: :send_email

  get 'export', to: 'organizations#export'
  get 'candidate_organization_duplicates', to: 'candidate_organizations#duplicates'
  get 'contact_duplicates', to: 'contacts#duplicates'
  get 'location_duplicates', to: 'locations#duplicates'
  get 'sector_duplicates', to: 'sectors#duplicates'
  get 'product_duplicates', to: 'products#duplicates'
  get 'building_block_duplicates', to: 'building_blocks#duplicates'
  get 'organization_duplicates', to: 'organizations#duplicates'
  get 'use_case_duplicates', to: 'use_cases#duplicates'
  get 'workflow_duplicates', to: 'workflows#duplicates'
  get 'glossary_duplicates', to: 'glossaries#duplicates'
  get 'deploys_refresh_list', to: 'deploys#refresh_list'
  get 'project_duplicates', to: 'projects#duplicates'
  get 'portal_view_duplicates', to: 'portal_views#duplicates'
  get 'use_case_step_duplicates', to: 'use_case_steps#duplicates'
  get 'tag_duplicates', to: 'tags#duplicates'
  get 'category_indicator_duplicates', to: 'category_indicators#duplicates'
  get 'handbook_duplicates', to: 'handbooks#duplicates'
  get 'handbook_page_duplicates', to: 'handbook_pages#duplicates'

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  attr_accessor :tag_desc

  has_many :tag_descriptions, dependent: :destroy

  scope :name_contains, ->(name) { where('LOWER(name) like LOWER(?)', "%#{name}%") }
  scope :slug_starts_with, ->(slug) { where('LOWER(slug) like LOWER(?)', "#{slug}\\_%") }

  def to_param
    slug
  end

  def tag_description_localized
    description = tag_descriptions.order(Arel.sql('LENGTH(description) DESC'))
                                  .find_by(locale: I18n.locale)
    if description.nil?
      description = tag_descriptions.order(Arel.sql('LENGTH(description) DESC'))
                                    .find_by(locale: 'en')
    end
    description
  end

  def self.serialization_options
    {
      except: %i[created_at updated_at]
    }
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_tag, only: %i[show edit update destroy]

  def unique_search
    record = Tag.find_by(slug: params[:id])
    return render(json: {}, status: :not_found) if record.nil?

    render(json: record.to_json(Tag.serialization_options))
  end

  def simple_search
    default_page_size = 20
    tags = Tag.order(:slug)

    current_page = 1
    current_page = params[:page].to_i if params[:page].present? && params[:page].to_i.positive?

    tags = tags.name_contains(params[:search]) if params[:search].present?

    tags = tags.paginate(page: current_page, per_page: default_page_size)

    results = {
      url: request.original_url,
      count: tags.count,
      page_size: default_page_size
    }

    results['next_page'] = current_page + 1 if tags.count > default_page_size * current_page

    results['previous_page'] = current_page - 1 if current_page > 1

    results['results'] = tags

    render(json: results.to_json(Tag.serialization_options))
  end

  def complex_search
    default_page_size = 20
    tags = Tag.order(:slug)

    current_page = 1
    current_page = params[:page].to_i if params[:page].present? && params[:page].to_i.positive?

    tags = tags.name_contains(params[:search]) if params[:search].present?

    tags = tags.paginate(page: current_page, per_page: default_page_size)

    results = {
      url: request.original_url,
      count: tags.count,
      page_size: default_page_size
    }

    results['next_page'] = current_page + 1 if tags.count > default_page_size * current_page

    results['previous_page'] = current_page - 1 if current_page > 1

    results['results'] = tags

    render(json: results.to_json(Tag.serialization_options))
  end

  # GET /tags
  # GET /tags.json
  def index
    if params[:without_paging]
      @tags = Tag.order(:name)
      !params[:search].blank? && @tags = @tags.name_contains(params[:search])
      authorize(@tags, :view_allowed?)
      return @tags
    end

    current_page = params[:page] || 1

    if params[:search]
      @tags = Tag.name_contains(params[:search])
                 .order(:name)
                 .paginate(page: current_page, per_page: 20)
    else
      @tags = Tag.order(:name)
                 .paginate(page: current_page, per_page: 20)
    end
    authorize(@tags, :view_allowed?)
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    authorize(@tag, :view_allowed?)
  end

  # GET /tags/new
  def new
    authorize(Tag, :mod_allowed?)
    @tag = Tag.new
    @tag_desc = TagDescription.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags
  # POST /tags.json
  def create
    authorize(Tag, :mod_allowed?)
    @tag = Tag.new(tag_params)
    @tag_desc = TagDescription.new

    respond_to do |format|
      if @tag.save
        if tag_params[:tag_desc]
          @tag_desc.tag_id = @tag.id
          @tag_desc.locale = I18n.locale
          @tag_desc.description = tag_params[:tag_desc]
          @tag_desc.save
        end
        format.html { redirect_to(tags_path, notice: 'Tag was successfully created.') }
        format.json { render(:show, status: :created, location: @tag) }
      else
        format.html { render(:new) }
        format.json { render(json: @tag.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    authorize(@tag, :mod_allowed?)
    if tag_params[:tag_desc]
      @tag_desc.tag_id = @tag.id
      @tag_desc.locale = I18n.locale
      @tag_desc.description = tag_params[:tag_desc]
      @tag_desc.save
    end
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to(tags_path, notice: 'Tag was successfully updated.') }
        format.json { render(:show, status: :ok, location: @tag) }
      else
        format.html { render(:edit) }
        format.json { render(json: @tag.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    authorize(@tag, :mod_allowed?)
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to(tags_url, notice: 'Tag was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  def duplicates
    @tags = []
    if params[:current].present?
      current_slug = slug_em(params[:current])
      original_slug = slug_em(params[:original])
      @tags = Tag.where(slug: current_slug).to_a if current_slug != original_slug
    end
    @tags = authorize(Tag, :view_allowed?)
    render(json: @tags, only: [:name])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find_by(slug: params[:id])
    @tag = Tag.find(params[:id]) if @tag.nil? && params[:id].scan(/\D/).empty?
    @tag_desc = TagDescription.where(tag_id: @tag.id, locale: I18n.locale).first
    @tag_desc ||= TagDescription.new
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:name, :slug, :tag_desc)
          .tap do |attr|
            if params[:reslug].present?
              attr[:slug] = slug_em(attr[:name])
              if params[:duplicate].present?
                first_duplicate = Tag.slug_starts_with(attr[:slug]).order(slug: :desc).first
                attr[:slug] = attr[:slug] + generate_offset(first_duplicate).to_s
              end
            end
          end
  end
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/tags/_form.html.erb
<% base_path = Rails.env.production? ? '/admin/' : '' %>
<%= form_with(model: tag, local: true, html: { id: 'tag-form' }, url: base_path + tag_path) do |form| %>

  <fieldset class="form-label-group">
    <%= form.text_field :name, id: :tag_name, class: "form-control", placeholder: t('view.general.name') %>
    <%= form.label :name, t('view.general.name') %>
  </fieldset>

  <div class="mt-2"></div>
  <input id="original_name" type="hidden" value="<%= tag.name %>" />
  <div id="duplicate-warning" class="alert alert-warning">
    <%= t('view.general.duplicates', model: t('model.use-case-step')) %>
  </div>

  <input type="hidden" id="tag_desc" name="tag[tag_desc]" />
  <div id="tag_editor"> </div>
  
  <fieldset class="float-right mt-4">
    <%= form.submit t('view.general.submit'), :class => "btn btn-primary", :id => "submit-btn" %>
    <%= link_to t('view.general.back'), "javascript:window.history.back()", :class => 'btn btn-outline-secondary' %>
  </fieldset>
<% end %>

<script>

$("#submit-btn").on('click', function(e) {
    var descHtml = descEditor.html.get()
    $("#tag_desc").val(descHtml)
  });

  var descEditor;
  $(document).ready(function() {
    descEditor = new FroalaEditor('#tag_editor', {
      key: "<%= ENV['FROALA_KEY'] %>",
      attribution: false,
      language: "<%= I18n.locale %>",
      imageUploadURL: '/froala_image/upload',
      imageUploadMethod: 'POST'
    }, function() {
      descEditor.html.set("<%= @tag_desc.description.nil? ? "" : @tag_desc.description.squish.gsub("\"","\\\"").html_safe %>")
    });
  });

</script>

app/views/tags/_tag.html.erb
<% base_path = Rails.env.production? ? '/admin/' : '' %>
<div class="card mt-2">
  <div class="card-body py-3 px-3">
    <div>
      <%= link_to(base_path + tag_path(tag)) do %>
        <%= "#{tag.name}" %>
      <% end %>
    </div>
    <div id="<%= tag.slug %>" class="wysiwyg-viewer">
        <%= tag.tag_descriptions.select { |desc| desc.locale == I18n.locale.to_s }.first && tag.tag_descriptions
        .select { |desc| desc.locale == I18n.locale.to_s }
        .first
        .description
        .html_safe %>
    </div>
    <p class="float-right mb-0">
      <% if user_signed_in? && policy(tag).mod_allowed? %>
        <%= link_to t('view.general.edit'), base_path + edit_tag_path(tag), :class => "card-link" %>
      <% end %>
    </p>
  </div>
</div>

app/views/tags/edit.html.erb
<% if @tag.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @tag.errors.count) %>
    </div>
  </div>
<% end %>
<div class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.edit', model: t('model.use-case-step')) %>
</div>
<%= render 'form', tag: @tag %>

app/views/tags/index.html.erb
<% base_path = Rails.env.production? ? '/admin/' : '' %>
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>

<div class="row">
  <div class="col-12">
    <% if user_signed_in? && policy(Tag).mod_allowed? %>
      <%= link_to(base_path + new_tag_path, class: 'btn btn-outline-secondary float-left') do %>
        <span class="d-none d-md-block">
          <%= "#{t('view.general.create')} #{t('model.tag').to_s.titlecase}" %>
        </span>
        <span class="d-block d-md-none">
          <i class="fa fa-plus fa-sm" aria-hidden="true"></i>
        </span>
      <% end %>
    <% end %>
    <div class="form-group float-right mb-0">
      <%= form_tag(base_path + tags_path, method: "get", id: "search-form", class: "form-inline") do %>
        <%= text_field_tag :search, params[:search], class: "form-control",
            placeholder: t('view.general.search-placeholder', model: t('model.tag').to_s.pluralize) %>
        <div class="input-group-append">
          <%= submit_tag t('view.general.search'), class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div id="tag-list" data-current-page="1">
  <%= render @tags %>
</div>

app/views/tags/index.js.erb
$('#tag-list').append('<%= j render(@tags) %>');
$('#tag-list > div:not(.existing-tag)').addClass('to-be-animated');
$(document).trigger("infinite-scroll");

app/views/tags/new.html.erb
<% if @tag.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @tag.errors.count) %>
    </div>
  </div>
<% end %>
<div class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.create', model: t('model.tag')) %>
</div>
<%= render 'form', tag: @tag %>

app/views/tags/show.html.erb
<% base_path = Rails.env.production? ? '/admin/' : '' %>
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>

<div class="card">
  <div class="card-body px-3 py-3">
    <div>
      <%= "#{t('model.tag').to_s.titlecase}: #{@tag.name}" %>
    </div>
    <div id="tag-viewer" class="wysiwyg-viewer">
      <%= @tag.tag_descriptions.select { |desc| desc.locale == I18n.locale.to_s }.first && @tag.tag_descriptions
            .select { |desc| desc.locale == I18n.locale.to_s }
            .first
            .description
            .html_safe %>
    </div>
    <p class="float-right mb-0" >
      <%= link_to t('view.general.back'), base_path + tags_path, :class => "card-link" %>
      <% if user_signed_in? && policy(@tag).mod_allowed? %>
        <%= link_to t('view.general.edit'), base_path + edit_tag_path(@tag), :class => "card-link" %>
      <% end %>
    </p>
  </div>
</div>