config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/server_error'
  mount(GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql') if Rails.env.development?

  post '/graphql', to: 'graphql#execute'

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  resources :task_trackers

  post '/entities/process-file', to: 'entities#process_file'

  resources :candidate_products do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :candidate_roles do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :glossaries
  resources :settings

  resources :rubric_categories, only: %i[index update create destroy]
  resources :category_indicators, only: %i[index update create destroy]
  resources :maturity_rubrics do
    resources :rubric_categories do
      resources :category_indicators
    end
  end

  resources :moves, only: %i[index update create destroy]
  resources :activities, only: %i[index update create destroy]

  resources :plays do
    resources :moves
  end

  resources :playbooks do
    post 'assign_play'
    post 'remove_play'
    resources :plays do
      resources :moves
    end
  end

  resources :handbook_pages, only: %i[index update create destroy]
  resources :handbooks do
    get 'count', on: :collection
    post 'upload_design_images', on: :collection
    member do
      post 'convert_pages'
    end
    resources :handbook_pages do
      member do
        get 'copy_page'
        get 'edit_content'
        get 'load_design'
        post 'save_design'
        patch 'save_design'
        get 'create_pdf'
        get 'show_pdf'
      end
    end
  end

  resources :tags
  resources :use_case_steps

  resources :projects do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_project'
      post 'unfavorite_project'
    end
  end

  get 'deploys/index'
  get 'about/learnmore'
  get 'about', to: 'about#index'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  scope '/devise' do
    resources :users do
      get 'statistics', on: :collection
      get 'export_data', on: :collection
    end
  end

  devise_scope :user do
    get '/users', to: 'users#index'
    get '/users/password', to: 'devise/passwords#new'
    post '/authenticate/credentials', to: 'authentication#sign_in_ux'
    post '/authenticate/auth0', to: 'authentication#sign_in_auth0'
    post '/authenticate/signup', to: 'authentication#sign_up_ux'
    get '/authenticate/token', to: 'authentication#fetch_token'
    delete '/auth/invalidate', to: 'authentication#invalidate_token'
    post '/auth/reset-password', to: 'authentication#reset_password'
    post '/auth/apply-reset-token', to: 'authentication#apply_reset_token'
    post '/auth/validate-reset-token', to: 'authentication#validate_reset_token'
  end

  root to: redirect(path: '/products')

  resources :covid, only: [:index]

  resources :candidate_organizations do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :portal_views do
    member do
      post 'select'
    end
  end

  resources :products do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_product'
      post 'unfavorite_product'
    end
  end

  resources :building_blocks do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :sustainable_development_goals, only: %i[index show] do
    get 'count', on: :collection
  end

  resources :sdg_targets, only: %i[index show]

  resources :use_case_steps, only: %i[new create edit update show]
  resources :use_cases do
    get 'count', on: :collection
    get 'export_data', on: :collection
    resources :use_case_steps, only: %i[new create edit update show]
    member do
      post 'favorite_use_case'
      post 'unfavorite_use_case'
    end
  end

  resources :workflows do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :deploys do
    get 'show_messages'
    post 'add_ssh_user'
  end

  resources :organizations do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  get :update_locale, controller: 'application'

  # Start of external API routes
  get 'api/v1/organizations/:id', to: 'organizations#unique_search'
  get 'api/v1/organizations', to: 'organizations#simple_search', defaults: { format: 'json' }
  post 'api/v1/organizations', to: 'organizations#complex_search', defaults: { format: 'json' }

  get 'api/v1/building_blocks/:id', to: 'building_blocks#unique_search'
  get 'api/v1/building_blocks', to: 'building_blocks#simple_search', defaults: { format: 'json' }
  post 'api/v1/building_blocks', to: 'building_blocks#complex_search', defaults: { format: 'json' }

  get 'api/v1/cities/:id', to: 'cities#unique_search'
  get 'api/v1/cities', to: 'cities#simple_search', defaults: { format: 'json' }

  get 'api/v1/countries/:id', to: 'countries#unique_search'
  get 'api/v1/countries', to: 'countries#simple_search', defaults: { format: 'json' }

  get 'api/v1/products/:id', to: 'products#unique_search'
  get 'api/v1/products', to: 'products#simple_search', defaults: { format: 'json' }
  post 'api/v1/products', to: 'products#complex_search', defaults: { format: 'json' }
  post 'api/v1/products/owners', to: 'products#owner_search', defaults: { format: 'json' }

  get 'api/v1/projects/:id', to: 'projects#unique_search'
  get 'api/v1/projects', to: 'projects#simple_search', defaults: { format: 'json' }
  post 'api/v1/projects', to: 'projects#complex_search', defaults: { format: 'json' }

  get 'api/v1/sectors/:id', to: 'sectors#unique_search'
  get 'api/v1/sectors', to: 'sectors#simple_search', defaults: { format: 'json' }

  get 'api/v1/sdgs/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sdgs', to: 'sustainable_development_goals#simple_search', defaults: { format: 'json' }
  post 'api/v1/sdgs', to: 'sustainable_development_goals#simple_search', defaults: { format: 'json' }

  get 'api/v1/sustainable_development_goals/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sustainable_development_goals', to: 'sustainable_development_goals#simple_search',
                                              defaults: { format: 'json' }

  get 'api/v1/tags/:id', to: 'tags#unique_search'
  get 'api/v1/tags', to: 'tags#simple_search', defaults: { format: 'json' }

  get 'api/v1/use_cases/:id', to: 'use_cases#unique_search'
  get 'api/v1/use_cases', to: 'use_cases#simple_search', defaults: { format: 'json' }
  post 'api/v1/use_cases', to: 'use_cases#complex_search', defaults: { format: 'json' }

  get 'api/v1/use_cases/:id/use_case_steps/:step_id', to: 'use_case_steps#unique_search'
  get 'api/v1/use_cases/:id/use_case_steps', to: 'use_case_steps#simple_search', defaults: { format: 'json' }

  get 'api/v1/workflows/:id', to: 'workflows#unique_search'
  get 'api/v1/workflows', to: 'workflows#simple_search', defaults: { format: 'json' }
  post 'api/v1/workflows', to: 'workflows#complex_search', defaults: { format: 'json' }

  # End of external API routes

  resources :operator_services
  resources :audits, only: [:index]
  resources :stylesheets

  resources :cities, only: %i[index show]
  resources :countries

  resources :locations do
    resources :organizations
  end

  resources :sectors do
    resources :organizations
    resources :use_cases
  end

  resources :contacts do
    resources :organizations
  end

  resources :tags
  resources :use_case_steps

  get '/object_counts', to: 'application#object_counts', as: :object_counts
  post '/add_filter', to: 'application#add_filter', as: :add_filter
  post '/add_filters', to: 'application#add_filters', as: :add_filters
  post '/remove_filter', to: 'application#remove_filter', as: :remove_filter
  post '/remove_all_filters', to: 'application#remove_all_filters', as: :remove_all_filters
  get '/fetch_filters', to: 'application#fetch_filters', as: :fetch_filters
  get '/agg_capabilities', to: 'organizations#agg_capabilities', as: :agg_capabilities
  get '/agg_services', to: 'organizations#agg_services', as: :agg_services
  get '/service_capabilities', to: 'organizations#service_capabilities', as: :service_capabilities
  get '/update_capability', to: 'organizations#update_capability', as: :update_capability
  get '/privacy', to: 'about#privacy', as: :privacy
  get '/terms', to: 'about#terms', as: :terms
  get '/healthcheck', to: 'about#healthcheck', as: :healthcheck

  post '/save_url', to: 'application#save_url', as: :save_url
  post '/remove_url', to: 'application#remove_url', as: :remove_url
  post '/send_email', to: 'application#send_email', as: :send_email

  get 'export', to: 'organizations#export'
  get 'candidate_organization_duplicates', to: 'candidate_organizations#duplicates'
  get 'contact_duplicates', to: 'contacts#duplicates'
  get 'location_duplicates', to: 'locations#duplicates'
  get 'sector_duplicates', to: 'sectors#duplicates'
  get 'product_duplicates', to: 'products#duplicates'
  get 'building_block_duplicates', to: 'building_blocks#duplicates'
  get 'organization_duplicates', to: 'organizations#duplicates'
  get 'use_case_duplicates', to: 'use_cases#duplicates'
  get 'workflow_duplicates', to: 'workflows#duplicates'
  get 'glossary_duplicates', to: 'glossaries#duplicates'
  get 'deploys_refresh_list', to: 'deploys#refresh_list'
  get 'project_duplicates', to: 'projects#duplicates'
  get 'portal_view_duplicates', to: 'portal_views#duplicates'
  get 'use_case_step_duplicates', to: 'use_case_steps#duplicates'
  get 'tag_duplicates', to: 'tags#duplicates'
  get 'category_indicator_duplicates', to: 'category_indicators#duplicates'
  get 'handbook_duplicates', to: 'handbooks#duplicates'
  get 'handbook_page_duplicates', to: 'handbook_pages#duplicates'

app/helpers/portal_views_helper.rb
# frozen_string_literal: true

module PortalViewsHelper
end

app/views/portal_views/edit.html.erb
<% if @portal_view.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @portal_view.errors.count) %>
    </div>
  </div>
<% end %>
<div class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.edit', model: t('model.portal-view')) %>
</div>
<%= render 'form', portal_view: @portal_view %>

app/views/portal_views/index.html.erb
<% base_path = Rails.env.production? ? '/admin/' : '' %>
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>

<% if user_signed_in? && policy(PortalView).mod_allowed? %>
  <%= link_to base_path + new_portal_view_path, class: 'btn btn-outline-secondary float-left ml-1' do %>
    <span class="d-none d-md-block"><%= t('view.general.create') %></span>
    <span class="d-block d-md-none">
      <i class="fa fa-plus fa-sm" aria-hidden="true"></i>
    </span>
  <% end %>
<% end %>
<div class="form-group float-right mb-2">
  <%= form_tag(portal_views_path, method: "get", id: "search-form", class: "form-inline") do %>
    <%= text_field_tag :search, params[:search], class: "form-control",
        placeholder: t('view.general.search-placeholder', model: t('model.portal-view').to_s.pluralize) %>
    <div class="input-group-append">
      <%= submit_tag t('view.general.search'), class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th class="d-none d-md-table-cell"><%= t('view.general.name') %></th>
      <th class="d-none d-md-table-cell"><%= t('view.general.description') %></th>
      <th class="d-none d-md-table-cell"><%= t('view.filternav.top-nav') %></th>
      <th class="d-none d-md-table-cell"><%= t('view.filternav.filter-nav') %></th>
      <th class="d-none d-md-table-cell"><%= t('view.filternav.user-role') %></th>
      <th class="d-table-cell d-md-none"><%= t('model.portal-view').titlecase %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @portal_views.count > 0 %>
      <% @portal_views.each do |portal_view| %>
        <tr>
          <td class="d-none d-md-table-cell"><%= portal_view.name %></td>
          <td class="d-none d-md-table-cell"><%= portal_view.description %></td>
          <td class="d-none d-md-table-cell">
            <%= portal_view.top_navs
                           .map { |key| I18n.translate("view.filternav.#{key}") }
                           .join(', ') %>
          </td>
          <td class="d-none d-md-table-cell">
            <%= portal_view.filter_navs
                           .map{ |key| I18n.translate("view.filternav.#{key}") }
                           .join(', ') %>
          </td>
          <td class="d-none d-md-table-cell">
            <%= portal_view.user_roles
                           .map{ |key| I18n.translate("view.user.role.#{key}") }
                           .join(', ') %>
          </td>
          <td class="d-table-cell d-md-none">
            <strong><%= portal_view.name %></strong>
            <div class="text-muted">
              <%= portal_view.description %>
            </div>
            <div class="text-muted">
              <span class="font-weight-bold"><%= t('view.filternav.top-nav') %>:</span>
              <%= portal_view.top_navs
                             .map { |key| I18n.translate("view.filternav.#{key}") }
                             .join(', ') %>.
            </div>
            <div class="text-muted">
              <span class="font-weight-bold"><%= t('view.filternav.top-nav') %>:</span>
              <%= portal_view.filter_navs
                             .map{ |key| I18n.translate("view.filternav.#{key}") }
                             .join(', ') %>.
            </div>
            <div class="text-muted">
              <span class="font-weight-bold"><%= t('view.filternav.user-role') %>:</span>
              <%= portal_view.user_roles
                             .map{ |key| I18n.translate("view.user.role.#{key}") }
                             .join(', ') %>.
            </div>
          </td>
          <td class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false" style="padding-top: 0;">
               <%= t('view.general.action') %>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <%= link_to t('view.general.view'), base_path + portal_view_path(portal_view), :class =>"dropdown-item" %>
              <% if user_signed_in? && policy(portal_view).mod_allowed? %>
                <%= link_to t('view.general.edit'), base_path + edit_portal_view_path(portal_view), :class =>"dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to t('view.general.delete'), portal_view_path(portal_view), method: :delete,
                    data: { confirm: t('view.general.delete-confirmation', model: t('model.portal-view')) },
                    class: "dropdown-item" %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="4">
          <small class="text-muted"><%= t('view.portal_view.index.no-data') %></small>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @portal_views, class: 'float-right digg-pagination', inner_window: 1 %>

app/views/portal_views/new.html.erb
<% if @portal_view.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @portal_view.errors.count) %>
    </div>
  </div>
<% end %>
<div class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.create', model: t('model.portal-view')) %>
</div>
<%= render 'form', portal_view: @portal_view %>

app/views/portal_views/show.html.erb
<% base_path = Rails.env.production? ? '/admin/' : '' %>
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>
<div class="card">
  <div class="card-header bg-secondary text-white">
    <%= "#{t('model.portal-view').to_s.titlecase}: #{@portal_view.name}" %>
  </div>
  <div class="card-body py-2">
    <div class="card-text text-muted mt-2 mb-2">
      <strong><%= t('view.general.description') %>:</strong>
      <%= @portal_view.description %> 
    </div>
    <div class="card-text text-muted mt-2 mb-2">
      <strong><%= t('view.portal.form.subdomain') %>:</strong>
      <%= @portal_view.subdomain %> 
    </div>
    <div class="float-right" >
      <%= link_to t('view.general.back'), base_path + portal_views_path, :class => "card-link" %>
      <% if user_signed_in? && policy(@portal_view).mod_allowed? %>
        <%= link_to t('view.general.edit'), base_path + edit_portal_view_path(@portal_view), :class => "card-link" %>
      <% end %>
    </div>
  </div>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal-view.top-nav').to_s.pluralize.titlecase %>
  </div>
  <% if @portal_view.top_navs.count > 0 %>
    <div class="row">
      <% @portal_view.top_navs.each do |top_nav| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body p-2">
              <div class="m-0"><%= I18n.translate("view.filternav.#{top_nav}") %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="card-text text-muted">
      <%= t('view.general.not-available', model: t('model.portal-view'), multi: t('view.portal-view.top-nav').to_s.pluralize) %>
    </p>
  <% end %>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal-view.filter-nav').to_s.pluralize.titlecase %>
  </div>
  <% if @portal_view.filter_navs.count > 0 %>
    <div class="row">
      <% @portal_view.filter_navs.each do |filter_nav| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body p-2">
              <div class="m-0"><%= I18n.translate("view.filternav.#{filter_nav}") %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="card-text text-muted">
      <%= t('view.general.not-available', model: t('model.portal-view'), multi: t('view.portal-view.filter-nav').to_s.pluralize) %>
    </p>
  <% end %>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal-view.user-role').to_s.pluralize.titlecase %>
  </div>
  <% if @portal_view.user_roles.count > 0 %>
    <div class="row">
      <% @portal_view.user_roles.each do |user_role| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body p-2">
              <div class="m-0"><%= I18n.translate("view.user.role.#{user_role}") %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="card-text text-muted">
      <%= t('view.general.not-available', model: t('model.portal-view'), multi: t('view.portal-view.filter-nav').to_s.pluralize) %>
    </p>
  <% end %>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('model.product').to_s.pluralize.titlecase %>
  </div>
  <% if @portal_view.product_views.count > 0 %>
    <div class="row">
      <% @portal_view.product_views.each do |origin| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body p-2">
              <div class="m-0"><%= origin %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="card-text text-muted">
      <%= t('view.general.not-available', model: t('model.portal-view'), multi: t('model.product').to_s.pluralize) %>
    </p>
  <% end %>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('model.organization').to_s.pluralize.titlecase %>
  </div>
  <% if @portal_view.organization_views.count > 0 %>
    <div class="row">
      <% @portal_view.organization_views.each do |org_type| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body p-2">
              <div class="m-0"><%= org_type %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="card-text text-muted">
      <%= t('view.general.not-available', model: t('model.portal-view'), multi: t('model.organization').to_s.pluralize) %>
    </p>
  <% end %>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal.index.landing-page') %>
  </div>
  <p class="m-2">
    <div id="about-page" class="wysiwyg-viewer">
        <%= @about_page.html_safe %>
    </div>
  </p>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal.index.background-color') %>
  </div>
  <p class="m-2">
    <div class="ml-3"><%= @stylesheet_color %></div>
  </p>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal.index.page-footer') %>
  </div>
  <p class="m-2">
    <div id="page-footer" class="wysiwyg-viewer">
        <%= @footer.html_safe %>
    </div>
  </p>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal.index.header-logo') %>
  </div>
  <%= image_tag "/assets/portal_views/"+ @portal_view.slug + ".png",
                alt: "DIAL Logo", height: "86px", style: "background-color: #ccc" %>
</div>