config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/server_error'
  mount(GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql') if Rails.env.development?

  post '/graphql', to: 'graphql#execute'

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  resources :task_trackers

  post '/entities/process-file', to: 'entities#process_file'

  resources :candidate_products do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :candidate_roles do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :glossaries
  resources :settings

  resources :rubric_categories, only: %i[index update create destroy]
  resources :category_indicators, only: %i[index update create destroy]
  resources :maturity_rubrics do
    resources :rubric_categories do
      resources :category_indicators
    end
  end

  resources :moves, only: %i[index update create destroy]
  resources :activities, only: %i[index update create destroy]

  resources :plays do
    resources :moves
  end

  resources :playbooks do
    post 'assign_play'
    post 'remove_play'
    resources :plays do
      resources :moves
    end
  end

  resources :handbook_pages, only: %i[index update create destroy]
  resources :handbooks do
    get 'count', on: :collection
    post 'upload_design_images', on: :collection
    member do
      post 'convert_pages'
    end
    resources :handbook_pages do
      member do
        get 'copy_page'
        get 'edit_content'
        get 'load_design'
        post 'save_design'
        patch 'save_design'
        get 'create_pdf'
        get 'show_pdf'
      end
    end
  end

  resources :tags
  resources :use_case_steps

  resources :projects do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_project'
      post 'unfavorite_project'
    end
  end

  get 'deploys/index'
  get 'about/learnmore'
  get 'about', to: 'about#index'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  scope '/devise' do
    resources :users do
      get 'statistics', on: :collection
      get 'export_data', on: :collection
    end
  end

  devise_scope :user do
    get '/users', to: 'users#index'
    get '/users/password', to: 'devise/passwords#new'
    post '/authenticate/credentials', to: 'authentication#sign_in_ux'
    post '/authenticate/auth0', to: 'authentication#sign_in_auth0'
    post '/authenticate/signup', to: 'authentication#sign_up_ux'
    get '/authenticate/token', to: 'authentication#fetch_token'
    delete '/auth/invalidate', to: 'authentication#invalidate_token'
    post '/auth/reset-password', to: 'authentication#reset_password'
    post '/auth/apply-reset-token', to: 'authentication#apply_reset_token'
    post '/auth/validate-reset-token', to: 'authentication#validate_reset_token'
  end

  root to: redirect(path: '/products')

  resources :covid, only: [:index]

  resources :candidate_organizations do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :portal_views do
    member do
      post 'select'
    end
  end

  resources :products do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_product'
      post 'unfavorite_product'
    end
  end

  resources :building_blocks do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :sustainable_development_goals, only: %i[index show] do
    get 'count', on: :collection
  end

  resources :sdg_targets, only: %i[index show]

  resources :use_case_steps, only: %i[new create edit update show]
  resources :use_cases do
    get 'count', on: :collection
    get 'export_data', on: :collection
    resources :use_case_steps, only: %i[new create edit update show]
    member do
      post 'favorite_use_case'
      post 'unfavorite_use_case'
    end
  end

  resources :workflows do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :deploys do
    get 'show_messages'
    post 'add_ssh_user'
  end

  resources :organizations do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  get :update_locale, controller: 'application'

  # Start of external API routes
  get 'api/v1/organizations/:id', to: 'organizations#unique_search'
  get 'api/v1/organizations', to: 'organizations#simple_search', defaults: { format: 'json' }
  post 'api/v1/organizations', to: 'organizations#complex_search', defaults: { format: 'json' }

  get 'api/v1/building_blocks/:id', to: 'building_blocks#unique_search'
  get 'api/v1/building_blocks', to: 'building_blocks#simple_search', defaults: { format: 'json' }
  post 'api/v1/building_blocks', to: 'building_blocks#complex_search', defaults: { format: 'json' }

  get 'api/v1/cities/:id', to: 'cities#unique_search'
  get 'api/v1/cities', to: 'cities#simple_search', defaults: { format: 'json' }

  get 'api/v1/countries/:id', to: 'countries#unique_search'
  get 'api/v1/countries', to: 'countries#simple_search', defaults: { format: 'json' }

  get 'api/v1/products/:id', to: 'products#unique_search'
  get 'api/v1/products', to: 'products#simple_search', defaults: { format: 'json' }
  post 'api/v1/products', to: 'products#complex_search', defaults: { format: 'json' }
  post 'api/v1/products/owners', to: 'products#owner_search', defaults: { format: 'json' }

  get 'api/v1/projects/:id', to: 'projects#unique_search'
  get 'api/v1/projects', to: 'projects#simple_search', defaults: { format: 'json' }
  post 'api/v1/projects', to: 'projects#complex_search', defaults: { format: 'json' }

  get 'api/v1/sectors/:id', to: 'sectors#unique_search'
  get 'api/v1/sectors', to: 'sectors#simple_search', defaults: { format: 'json' }

  get 'api/v1/sdgs/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sdgs', to: 'sustainable_development_goals#simple_search', defaults: { format: 'json' }
  post 'api/v1/sdgs', to: 'sustainable_development_goals#simple_search', defaults: { format: 'json' }

  get 'api/v1/sustainable_development_goals/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sustainable_development_goals', to: 'sustainable_development_goals#simple_search',
                                              defaults: { format: 'json' }

  get 'api/v1/tags/:id', to: 'tags#unique_search'
  get 'api/v1/tags', to: 'tags#simple_search', defaults: { format: 'json' }

  get 'api/v1/use_cases/:id', to: 'use_cases#unique_search'
  get 'api/v1/use_cases', to: 'use_cases#simple_search', defaults: { format: 'json' }
  post 'api/v1/use_cases', to: 'use_cases#complex_search', defaults: { format: 'json' }

  get 'api/v1/use_cases/:id/use_case_steps/:step_id', to: 'use_case_steps#unique_search'
  get 'api/v1/use_cases/:id/use_case_steps', to: 'use_case_steps#simple_search', defaults: { format: 'json' }

  get 'api/v1/workflows/:id', to: 'workflows#unique_search'
  get 'api/v1/workflows', to: 'workflows#simple_search', defaults: { format: 'json' }
  post 'api/v1/workflows', to: 'workflows#complex_search', defaults: { format: 'json' }

  # End of external API routes

  resources :operator_services
  resources :audits, only: [:index]
  resources :stylesheets

  resources :cities, only: %i[index show]
  resources :countries

  resources :locations do
    resources :organizations
  end

  resources :sectors do
    resources :organizations
    resources :use_cases
  end

  resources :contacts do
    resources :organizations
  end

  resources :tags
  resources :use_case_steps

  get '/object_counts', to: 'application#object_counts', as: :object_counts
  post '/add_filter', to: 'application#add_filter', as: :add_filter
  post '/add_filters', to: 'application#add_filters', as: :add_filters
  post '/remove_filter', to: 'application#remove_filter', as: :remove_filter
  post '/remove_all_filters', to: 'application#remove_all_filters', as: :remove_all_filters
  get '/fetch_filters', to: 'application#fetch_filters', as: :fetch_filters
  get '/agg_capabilities', to: 'organizations#agg_capabilities', as: :agg_capabilities
  get '/agg_services', to: 'organizations#agg_services', as: :agg_services
  get '/service_capabilities', to: 'organizations#service_capabilities', as: :service_capabilities
  get '/update_capability', to: 'organizations#update_capability', as: :update_capability
  get '/privacy', to: 'about#privacy', as: :privacy
  get '/terms', to: 'about#terms', as: :terms
  get '/healthcheck', to: 'about#healthcheck', as: :healthcheck

  post '/save_url', to: 'application#save_url', as: :save_url
  post '/remove_url', to: 'application#remove_url', as: :remove_url
  post '/send_email', to: 'application#send_email', as: :send_email

  get 'export', to: 'organizations#export'
  get 'candidate_organization_duplicates', to: 'candidate_organizations#duplicates'
  get 'contact_duplicates', to: 'contacts#duplicates'
  get 'location_duplicates', to: 'locations#duplicates'
  get 'sector_duplicates', to: 'sectors#duplicates'
  get 'product_duplicates', to: 'products#duplicates'
  get 'building_block_duplicates', to: 'building_blocks#duplicates'
  get 'organization_duplicates', to: 'organizations#duplicates'
  get 'use_case_duplicates', to: 'use_cases#duplicates'
  get 'workflow_duplicates', to: 'workflows#duplicates'
  get 'glossary_duplicates', to: 'glossaries#duplicates'
  get 'deploys_refresh_list', to: 'deploys#refresh_list'
  get 'project_duplicates', to: 'projects#duplicates'
  get 'portal_view_duplicates', to: 'portal_views#duplicates'
  get 'use_case_step_duplicates', to: 'use_case_steps#duplicates'
  get 'tag_duplicates', to: 'tags#duplicates'
  get 'category_indicator_duplicates', to: 'category_indicators#duplicates'
  get 'handbook_duplicates', to: 'handbooks#duplicates'
  get 'handbook_page_duplicates', to: 'handbook_pages#duplicates'

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def learnmore; end

  def index
    stylesheet = Stylesheet.where(portal: session[:portal]['slug']).first
    @about_page = stylesheet.about_page
    @footer = stylesheet.footer_content
  end

  def privacy; end

  def terms; end

  def healthcheck
    sys_command = "PGPASSWORD='#{ENV['DATABASE_PASSWORD']}' psql -h #{ENV['DATABASE_HOST']} " \
                  "-U #{ENV['DATABASE_USER']} -d #{ENV['DATABASE_NAME']} -p #{ENV['DATABASE_PORT']} -c '\\q'"

    db_health = system(sys_command)

    render(json: { "webapp": true, "psql": db_health })
  end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

module AboutHelper
end

app/views/about/cookies.html.haml
%h2 COOKIES

%p Cookies are small text files which are downloaded to your computer, tablet or mobile phone when you visit a website or application. The website or application may retrieve these cookies from your web browser (eg Internet Explorer, Mozilla Firefox or Google Chrome) each time you visit, so they can recognise you, remember your preferences and provide you with a more secure online experience.

%p Generally, cookies are very useful and are a common method used by almost every website you visit because they help to make your online experience as smooth as possible. For security reasons, many websites will not function at all without the use of cookies (or other similar technologies, such as "web beacons" or "tags").

%p Cookies generally do not hold any information to identify an individual person, but are instead used to identify a browser on an individual machine.

%p If you prefer, you can restrict, block or delete cookies by changing your browser settings but that may mean that the website won't work properly

%p For more information about cookies and their impact on you and your browsing visit #{link_to 'http://www.aboutcookies.org', 'www.aboutcookies.org'}.


%h2 TYPES OF COOKIES

%h3 Necessary cookies

%p These cookies are essential in helping you to make use of the features and services we offer on the DIAL product registry website. Without these cookies, the services you want to use cannot be provided. These cookies do not gather information about you that could be used to identify you, and they do not monitor or remember where you have been on the internet.

%h3 Functional cookies

%p These cookies allow us to provide you with a better online experience when you use our website. They do not gather or store any information which would allow us to identify you personally.

%h3 Performance cookies

%p Performance cookies help us to understand how our customers use our site, so we can keep our products and services relevant, easy to use and up to date. For example, we can see which products and services are most popular, identify when and where errors occur, and test different versions of a page in order to provide an improved online experience.

%p Sometimes, the services we use to collect this information may be operated by other companies on our behalf. They may use similar technologies to cookies, known as "web beacons" or "tags". These are anonymous and, as they are only used for statistical purposes, they do not contain or collect any information that identifies you.

%h3 Targeting cookies

%p We have relationships with carefully selected and monitored suppliers (third parties) who may also set cookies during your visit. The purpose of these cookies is "behavioural advertising" (also known as "behavioural targeting" or "remarketing"), which is a means of showing you relevant products and services based on what you appear to be interested in. Although these cookies can track your visits around the web they don't know who you are. Without these cookies, online advertisements you encounter will be less relevant to you and your interests.


%h2 MANAGING COOKIES

%p Most internet browsers allow you to erase cookies from your computer hard drive, block all cookies (or just third-party cookies) or warn you before a cookie is stored on your device.

%p Please note, if you choose to block all cookies, our site will not function as intended and you will not be able to use or access many of the services we provide. If you have blocked all cookies and wish to make full use of the features and services we offer, you will need to enable your cookies. You can do this in your browser (see below).

%p Rather than blocking all cookies, you can choose to only block third-party cookies which will still allow our website to function as intended.

%h3 How to manage cookies on your PC

%p To enable cookies on our website, follow the steps below.

%h4 Google Chrome

%ol
  %li Click "Tools" at the top of your browser and select "Settings".
  %li Click "Show advanced settings", scroll down to the section "Privacy" and click "Content Settings."
  %li Select "Allow local data to be set". To only acept first-party cookies, check the box next to "Block all third-party cookies without exception"

%h4 Microsoft Internet Explorer 6.0, 7.0, 8.0, 9.0

%ol
  %li Click "Tools" at the top of your browser and select "Internet Options", then click the "Privacy" tab.
  %li Check that the level of your privacy is set to Medium or lower, which will allow the use of cookies in your browser.
  %li If set above medium level it will prevent the use of cookies.

%h4 Mozilla Firefox

%ol
  %li Click "Tools" at the top of your browser and select "Options".
  %li Then select the "Privacy" icon.
  %li Click the "Cookies" and select "Allow pages to create a cookie."

%h4 Safari

%ol
  %li Click the gear icon at the top of your browser and select "Settings".
  %li Click the "Privacy" tab, then select the option "Disable the use of cookies by third parties and advertising cookies."
  %li Click "Save".

%h3 How to manage cookies on your Mac

%p To enable cookies on our website, follow the steps below.

%h4 Microsoft Internet Explorer 5.0 on OSX

%ol
  %li Click on "Explorer" at the top of your browser and select "Settings".
  %li Scroll down to the "Cookies" section in the "Received Files".
  %li Select "Do not ask."

%h4 Safari on OSX

%ol
  %li Click "Safari" on the top of your browser and select "Settings".
  %li Click the "Privacy" and then "Enable cookies."
  %li Select "only the pages you have visited."

%h4 Mozilla and Netscape on OSX

%ol
  %li Click "Mozilla" or "Netscape" at the top of your browser and select "Settings".
  %li Scroll down to the "Cookies" under "Privacy & Security".
  %li Select "Allow cookies only to the original site."

%h4 Opera

%ol
  %li Click "Menu" on the top of your browser and select "Settings".
  %li Then select "Options" tab and the "Advanced".
  %li Select "Enable cookies."

app/views/about/index.html.erb
<div class="alert alert-info my-2 text-center" role="alert">
  <%= t("view.about.help") %>
  <a href="https://docs.osc.dial.community/projects/product-registry/en/latest/" target="_blank">
    <%= t("view.about.help_link") %>
  </a>
</div>
<div class="alert alert-info mb-2 text-center" role="alert" id="active-users">
</div>
<% if session[:portal]["slug"] == "default" %>
<div id="covid-section" class="about-jumbotron">
  <h1 class="display-5 text-muted">DIAL Online Catalog Supports COVID-19 Response</h1>
  <div class="mb-5">
    <%= link_to 'Learn More', covid_index_path, :class => 'btn btn-outline-secondary float-left col-lg-2' %>
  </div>
</div>
<div id="intro_section" class="view jarallax main-img">
    <%= image_tag("ict_cover.png", class:'jarallax-img') %>
    <div class="mask purple-slight" style="height: 100vh;">
    <div class="container flex-center text-center">
      <div class="top-no-hover">
      <%= link_to products_path, class: 'no-hover' do %>
        <div class="text-white icon-inline"><%= t("view.about.enter_catalog") %></div>
        <i class="fas fa-external-link-alt text-white icon-inline"></i>
      <% end %>
      </div>
      <div class="row mt-4">
        <div class="col-md-12 col-xl-8 mx-auto">
          <h1 class="display-3 font-weight-bold mb-2 text-white"><%= t('view.about.sdg_title') %></h1>
          <h3 class="text-white"><%= t('view.about.sdg_subtitle') %></h3>
          </h1>
        </div>
      </div>
    </div>
    </div>
</div>


<div id="overview_section" class="container">
  <div class="row my-5 py-4">
    <div class="col-md-12 text-center">
        <p class="text-muted" align="justify"><%= t('view.about.explanation1') %></p>
        <p class="text-muted" align="justify"><%= t('view.about.explanation2') %></p>
        <p class="text-muted" align="justify"><%= t('view.about.explanation3') %></p>
        <div class="row flex-image-center">
            <div class="col-lg-2 m-2">
                <%= link_to image_tag("sdgs.png", width: 150, height:150, class: "clickable-image"), {action:'index', controller: "sustainable_development_goals"} %>
            </div>
            <div class="col-lg-6 m-2">
                <h3 class="text-muted ml-1 text-left"><%= link_to t("view.about.sdgs"), sustainable_development_goals_path, class: 'text_muted' %></h3>
                <p class="text-muted ml-1 text-left"><%= t('view.about.sdg_desc') %><p>
            </div>
        </div>
        <div class="row flex-image-center">
            <div class="col-lg-2 m-2">
                <%= link_to image_tag("use_cases.png", width: 150, height: 150, class: "clickable-image"), {action:'index', controller: "use_cases"} %>
            </div>
            <div class="col-lg-6 m-2">
                <h3 class="text-muted ml-1 text-left"><%= link_to t("view.about.use_cases"), use_cases_path, class: 'text_muted' %></h3>
                <p class="text-muted ml-1 text-left"><%= t('view.about.use_case_desc') %><p>
            </div>
        </div>
        <div class="row flex-image-center">
            <div class="col-lg-2 m-2">
                <%= link_to image_tag("workflows.png", width: 150, height:150, class: "clickable-image"), {action:'index', controller: "workflows"} %>
            </div>
            <div class="col-lg-6 m-2">
                <h3 class="text-muted ml-1 text-left"><%= link_to t("view.about.workflows"), workflows_path, class: 'text_muted' %></h3>
                <p class="text-muted ml-1 text-left"><%= t('view.about.workflow_desc') %><p>
            </div>
        </div>
        <div class="row flex-image-center">
            <div class="col-lg-2 m-2">
                <%= link_to image_tag("bbs.png", width: 150, height:150, class: "clickable-image"), {action:'index', controller: "building_blocks"} %>
            </div>
            <div class="col-lg-6 m-2">
                <h3 class="text-muted ml-1 text-left"><%= link_to t("view.about.bbs"), building_blocks_path, class: 'text_muted' %></h3>
                <p class="text-muted ml-1 text-left"><%= t('view.about.bb_desc') %><p>
            </div>
        </div>
        <div class="row flex-image-center">
            <div class="col-lg-2 m-2">
                <%= link_to image_tag("product1.svg", width: 150, height:150, class: "clickable-image"), {action:'index', controller: "products"} %>
            </div>
            <div class="col-lg-6 m-2">
                <h3 class="text-muted ml-1 text-left"><%= link_to t("view.about.products"), products_path, class: 'text_muted' %></h3>
                <p class="text-muted ml-1 text-left"><%= t('view.about.product_desc') %><p>
            </div>
        </div>
        <div class="row mt-3 mb-1 flex-image-center">
            <%= link_to t('view.about.read_more'), "https://digitalimpactalliance.org/wp-content/uploads/2019/04/D-STR-DIGITAL.02-2019-PDF-E.pdf", :class => 'btn btn-outline-secondary float-left m-2 col-lg-2 pr-1', target: :_blank %>
            <button type="button" class="btn btn-outline-secondary float-left m-2 col-lg-2 pr-1" data-toggle="modal" data-target="#myModal"><%= t('view.about.watch_video') %></button>
            <%= link_to t('view.about.launch'), use_cases_path, :class => 'btn btn-outline-secondary float-right m-2 col-lg-2 pr-3' %>
        </div>
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body">
                <iframe src="https://www.youtube.com/embed/Lvo30Fra2k0?rel=0&autoplay=0&enablejsapi=1" width=400 height=300></iframe>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('view.about.close') %></button>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

<div class="view jarallax" data-speed="1.0" style="height: 100vh;">
  <%= image_tag("image_2.png", class:'jarallax-img') %>
</div>

<div id="donor_section" class="container">
  <div class="row my-5 py-4 justify-content-md-center">
    <div class="col-md-6 text-center text-muted">
        <h2><%= t('view.about.donors') %></h2>
        <p class="text-muted" align="justify"><%= t('view.about.donors_text1') %></p>
        <%= link_to image_tag("sdgs.png", width: 150, height:150, class: "clickable-image"), {action:'index', controller: "sustainable_development_goals"} %>
        <h4 class="text-muted mt-2"><%= link_to t("view.about.donors_link"), sustainable_development_goals_path %></h4>
    </div>
  </div>
</div>

<div class="view jarallax" data-speed="1.0" style="height: 100vh;">
  <%= image_tag("image_3.png", class:'jarallax-img') %>
</div>

<div id="policy_section" class="container">
  <div class="row my-5 py-4">
    <div class="col-md-6 text-center text-muted">
        <h2><%= t('view.about.policy_makers') %></h2>
        <p class="text-muted" align="justify"><%= t('view.about.policy_text1') %>
        </p>
        <div class="about-image">
        <%= link_to image_tag("use_cases.png", width: 150, height: 150, class: "clickable-image"), {action:'index', controller: "use_cases"} %>
        <h4 class="text-muted mt-2"><%= link_to t("view.about.policy_link"), use_cases_path %></h4>
        </div>
    </div>
    <div class="col-md-6 text-center text-muted">
        <h2><%= t('view.about.implementers') %></h2>
        <p class="text-muted" align="justify"><%= t('view.about.implementers_text1') %>
        </p>
        <p class="pt-5"></p>
        <div class="about-image">
        <%= link_to image_tag("workflows.png", width: 150, height:150, class: "clickable-image"), {action:'index', controller: "workflows"} %>
        <h4 class="text-muted mt-2"><%= link_to t("view.about.implementers_link"), workflows_path %></h4>
        </div>
    </div>
  </div>
</div>

<div class="view jarallax" data-speed="1.0" style="height: 100vh;">
  <%= image_tag("image_4.png", class:'jarallax-img') %>
</div>

<div id="implement_section" class="container">
  <div class="row my-5 py-4">
    <div class="col-md-6 text-center text-muted">
        <h2><%= t('view.about.ict_ministers') %></h2>
        <p class="text-muted" align="justify"><%= t('view.about.ict_text1') %>
        </p>
        <div class="about-image">
        <%= link_to image_tag("bbs.png", width: 150, height:150, class: "clickable-image"), {action:'index', controller: "building_blocks"} %>
        <h4 class="text-muted mt-2"><%= link_to t("view.about.ict_link"), building_blocks_path %></h4>
        </div>
    </div>
    <div class="col-md-6 text-center text-muted">
        <h2><%= t('view.about.specialists') %></h2>
        <p class="text-muted" align="justify"><%= t('view.about.specialists_text1') %>
        </p>
        <p class="pt-2"></p>
        <div class="about-image">
        <%= link_to image_tag("product1.svg", width: 150, height:150, class: "clickable-image"), {action:'index', controller: "products"} %>
        <h4 class="text-muted mt-2"><%= link_to t("view.about.specialists_link"), products_path %></h4>
        </div>
    </div>
  </div>

  <div id="implement_section" class="container">
    <div class="row mt-3 mb-1 flex-image-center">
      <%= link_to t('view.about.contact'), "https://digitalimpactalliance.org/research/sdg-digital-investment-framework/",
                  target: "_blank", rel: "noreferrer noopener", :class => 'btn btn-outline-secondary float-left m-2 col-lg-2 pr-1',
                  'data-toggle'=>"tooltip", 'data-placement'=>"top", 'data-original-title'=>t('view.about.contact_text') %>
    </div>
    <div class="row mt-3 mb-1 flex-image-center">
      <p class="text-muted"><%= t('view.about.itu') %>
    </div>
  </div>
</div>
<% else %>
  <div id="about-viewer" class="wysiwyg-viewer">
    <%= @about_page.html_safe %>
  </div>
<% end %>

<%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jarallax/1.12.0/jarallax.min.js", async: true, onload: 'initJarallax()' %>
<script>

    function initJarallax() {
      /* init Jarallax */
      $('.jarallax').jarallax({
        speed: 0.2
      });

      $('.jarallax-keep-img').jarallax({
        keepImg: true,
      });
    }

    function formatDate(date) {
      var d = new Date(date),
          month = '' + (d.getMonth() + 1),
          day = '' + d.getDate(),
          year = d.getFullYear();

      if (month.length < 2) 
          month = '0' + month;
      if (day.length < 2) 
          day = '0' + day;

      return [year, month, day].join('-');
    }

    // Query users from Matomo analytics data
    var usersToday = new Date()
    var usersYesterday = new Date(usersToday)
    usersYesterday.setDate(usersYesterday.getDate() - 1)

    var url = "https://stats.dial.community?module=API&method=VisitsSummary.getVisits";
    url += "&idSite=7&period=range&date="+formatDate(usersYesterday)+","+formatDate(usersToday)+"&format=JSON&token_auth=anonymous";

    $.ajax({
        type: "GET",
        url: url,
        dataType: 'jsonp',
        crossDomain: true,
        success: function (data){
            $("#active-users").html("<%= t('view.about.active_users') %>: "+data.value)
        }
    });

</script>